# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - redis:latest
  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
stages:
  - install_deps
  - test_backend
  - run_build
  - test_frontend
cache:
  paths:
  - frontend/node_modules/
  - frontend/dist/
install_deps:
  stage: install_deps
  script:
   - cd frontend
   - npm install
test_backend:
  stage: test_backend
  script:
   - ./manage.py test backend.tests
   - ./manage.py test backend.customer_tests
run_build:
  stage: run_build
  script:
   - cd frontend
   - npm run build
test_frontend:
  stage: test_frontend
  script:
   - cd frontend
   - npm run unit
