# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('state', models.IntegerField(default=0)),
                ('service_number', models.IntegerField(default=0)),
                ('last_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('EID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('robot_icon', models.CharField(max_length=50)),
                ('robot_name', models.CharField(max_length=10)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=50)),
                ('RID', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='EID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Enterprise'),
        ),
    ]
