# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salt',
            field=models.CharField(default='11111111', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='salt',
            field=models.CharField(default='11111111', max_length=8),
            preserve_default=False,
        ),
    ]
